### ISSUE TITLE
Test any server given its url

### ISSUE THREAD

**Issue by phidias** [krajzeg/chaplain#1]
Hi Kuba,

I would like to use chaplain for testing an application that is written with Scala Play Framework - not an express js app. Is it a lot of effort to support this? I can help with coding if it's not in your priorities.

Thx,
Avgoustinos

**Comment by phidias** [comment]
Ideally I would like to be able to specify the app url through config & use relative urls inside the tests as it's done now.

`config({app: 'http://localhost:9000'});`

**Comment by krajzeg** [comment]
This is in fact pretty easy, and one of the things I intended to add pretty soon - so I can bump it up a little bit on the priority list. Expect it pretty soon on master, and then it'll go to the next npm release.

It'll probably look something like this:

```
config({
  server: 'http://localhost:9000'
});
```

In the current version, there are two different properties to give chaplain an HTTP server: `app` for testing against an app instance, and `server` for when you have an `http.Server` instance. I'm thinking of merging them into one `server` property to avoid forcing people to remember a lot of names - so this would fit right in as the third option for what that property can be.

**Comment by phidias** [comment]
Ok great! Thx. `server` property will be good.

**Comment by krajzeg** [comment]
The relevant commit has landed in master: https://github.com/krajzeg/chaplain/commit/c758e448c10b768ddbee037eb6a7d2ab5ec18160. You can just use `{server: 'http://localhost:12345/'}`, or any other URL prefix you want.

If you like, you can also use the newly added `before()` and `after()` to start/stop your test server with something like [command-promise](https://www.npmjs.com/package/command-promise):

```
  before(function() { return Command('./server start'); });
  after(function() { return Command('./server stop'); });
```

Both accept a function that should return a promise to wait on. If you don't want to fiddle with that, you can always just `./run-my-server && chaplain && ./stop-my-server`, I guess.

This is available on master only for now, I still have to document all changes before releasing the next version on npm.

**Comment by krajzeg** [comment]
This functionality is now released as part of 0.3.2.

**Comment by phidias** [comment]
That was quick! Thx! Will give it a try this week. aK

**Comment by krajzeg** [comment]
Let me know if you run into any more issues - still very actively looking for areas to improve :)
