### ISSUE TITLE
Ignore properties of objects in an Array

### ISSUE THREAD

**Issue by rivierasolutions** [krajzeg/chaplain#4]
Suppose my test produces the output:

```
[
  {
    "id": "e6a38a02-b0b8-4788-a276-f053c8a04d12",
    "name": "test user",
    "birthday": "2010-01-01T00:00:00.000Z",
    "createdAt": "2016-06-03T15:10:46.000Z",
    "updatedAt": "2016-06-03T15:10:46.000Z",
    "languageId": "89a0adbe-2732-11e6-946b-8cdcd4cc71dd"
  },
  {
    "id": "db048cc4-d765-4b86-b427-1bd272734d07",
    "name": "test user 2",
    "birthday": "2010-01-01T00:00:00.000Z",
    "createdAt": "2016-06-03T15:10:46.000Z",
    "updatedAt": "2016-06-03T15:10:46.000Z",
    "languageId": "89a0adbe-2732-11e6-946b-8cdcd4cc71dd"
  },
  {
    "id": "18e47607-332a-45a9-9cfa-7f837989432a",
    "name": "test user 3",
    "birthday": "2010-01-01T00:00:00.000Z",
    "createdAt": "2016-06-03T15:10:46.000Z",
    "updatedAt": "2016-06-03T15:10:46.000Z",
    "languageId": "89a0adbe-2732-11e6-946b-8cdcd4cc71dd"
  }
]
```

And I want to ignore the id, createdAt and updatedAt properties for each item. In the current version I have to do something like:

```
config({
        app: collectionServer,
        json: {
            ignore: ['[0].id', '[1].id', '[2].id', '[0].createdAt', '[1].createdAt', '[2].createdAt', '[0].updatedAt', '[1].updatedAt', '[2].updatedAt']
        }
    });
```

This causes problems e.g. when I wish to have another test in the same suite that will return only one item in the array. In that specific case chaplain will return an error. 
I would like to have something along the lines of

```
config({
        app: collectionServer,
        json: {
            ignore: [ '[].id', '[].createdAt', '[].updatedAt' ]
        }
    });
```

Which will allow me to ignore the properties in all items.

**Comment by krajzeg** [comment]
This is part of the planned improvements to the JSON format - giving it more power to ignore whatever you want to. 

I'm looking at [JSONPath](https://www.npmjs.com/package/JSONPath) and [json-path](ironically, two very different modules), which would let you express what you want as something like `[*].id` (ignore all IDs in the array) or `..id` (ignore all ID properties anywhere).

This is a matter where some research on how to do it is needed - I'll give you more info once that's done (Monday-ish).

**Comment by krajzeg** [comment]
Hey, support for generic ignores in JSON just landed on master :). If you'd like to check it out, it's there - the only thing that changed is that chaplain now supports [jsonpath](https://www.npmjs.com/package/jsonpath#jsonpath-syntax)-compatible paths in the `ignore` property (optionally without the $ to keep it more readable). 

So, `ignore: ['..id', '..createdAt', '..updatedAt']` should sort your tests out nicely.

**Comment by rivierasolutions** [comment]
Works flawlessly. Thank you.
