### ISSUE TITLE
Move test status to a more visible place

### ISSUE THREAD

**Issue by phidias** [krajzeg/chaplain#8]
Hi there,

It's hard to recognise in the console that a test is new. It writes ".. is newly added" but it's very hard to notice. Is it possible to make it more visible? Something like "[NEW] test name ..."?

aK

**Comment by krajzeg** [comment]
Seems like something to improve. I didn't anticipate that people would use long, mocha-like test descriptions, and in this situation the status at the end doesn't quite work. Might make sense to move it to the beginning and emphasize it more :).

**Comment by phidias** [comment]
thx for considering it

**Comment by krajzeg** [comment]
This is now changed on master - the new format is "NEW/CHANGED/ETC: <test name>". Will be released with the next version.

**Comment by phidias** [comment]
Cool thanks!
